/*
 * This source file was generated by the Gradle 'init' task
 */
package bot_hercule2;

public class App {
    public String getGreeting() {
        return "NexLogix Project";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
